# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9597587b674a142f164ebce9330c384f5a640b6f1d521e272946aba1dfa0cc58b47b277a2ddf8f3758bf93a6b1081154a0ea108e99ad6acadf7f364d1363e56

test:
  secret_key_base: 9b48513c57d00a626226e8ddf6fa0cf7b440f4ba623ff29a5b89e3ac0941f2c6b3477bbccf624408302644c4a1fe8b090129db89605345399111646041866c32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
